### ISSUE TITLE
scripts and scope

### ISSUE THREAD

**Issue by GoZOo** [opi/basement#6]
tu fais un print de $scripts & $page_bottom a la fin du fichier html.tpl.php, sauf que $scripts est rempli par défaut par les drupal_add_js ayant le scope header (scope par défaut) et page_bottom a les script avec pour scope footer.
Du coup, tous les scripts sont forcément placés en footer, il est impossible de placer des scripts dans le head si jamais on le souhaite (ex: option de google analytics pour choisir si on place le script en en-tête ou footer)

A voir si tu veux forcer tous les scripts a passer en scope footer : https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_js_alter/7

**Comment by opi** [comment]
Done with 2cc63e936ec7c5ef848d65bcab1edef466996e8c
