### ISSUE TITLE
Add a readme.txt file

### ISSUE THREAD

**Issue by lor** [opi/basement#8]
A readme.txt file at the project root should be welcome ;)

It could be have a short description of the philosophy and features of this started theme, and some useful commands as :
# Drush commands to rename your theme

drush basement-construct "My theme name" --machine-name=mythemename
drush basement-construct "My theme name" --destination=sites/all/themes/custom

Thanx a lot for the work and this very useful tool!

**Comment by opi** [comment]
0a842972466e64ddd0729f1a742628bc640d869e
